name: "Update Vatglasses data"

on:
    schedule:
        - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    # update all git submodules
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update submodules
              run: git submodule update --init --recursive
            - uses: stefanzweifel/git-auto-commit-action@v5
